# Project configuration

NETWORK = "CI"
STATION_CANDIDATES = ["LRL", "CLC", "SRT", "CCC", "TOW2"]
CHANNEL = "BHZ"
START_TIME = "2019-07-04"
END_TIME = "2019-07-20"
MIN_MAGNITUDE = 2.5
WINDOW_SECONDS = 30
TARGET_SAMPLE_RATE = 40
WARMUP_SECONDS = 25
MAX_POSITIVES = 500
NEG_TO_POS_RATIO = 1
OUT_PREFIX = "seismic_dataset_v3"
